---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCCluster
metadata:
  name: ibm-vpc-2
spec:
  region: "us-sout-1"
  resourceGroup: "823edda102129f3232a0dc065536fd72"
  vpc: "zwtzhang-vpc-2"
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ibm-vpc-2
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCCluster
    name: ibm-vpc-2
    namespace: default