---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: ibm-vpc-1
spec:
  region: "us-sout-1"
  resourceGroup: "823edda102129f3232a0dc065536fd72"
  vpc: "zwtzhang-vpc-1"
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: ibm-vpc-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCCluster
    name: ibm-vpc-1
    namespace: default
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: ibm-vpc-1-control-plane
    namespace: default
  controlPlaneEndpoint:
    host: 172.17.0.3
    port: 6443