---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc
  name: ibm-vpc
spec:
  region: "us-sout-1"
  resourceGroup: "4f15679623607b855b1a27a67f20e1c7"
  vpc: "zwtzhang-vpc"
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc
  name: ibm-vpc
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCCluster
    name: ibm-vpc
    namespace: default
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: ibm-vpc-control-plane
    namespace: default
  controlPlaneEndpoint:
    host: 150.238.51.93
    port: 6443