apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
    cluster.x-k8s.io/control-plane: ""
  name: controlplane-1-config
  namespace: default
spec:
  clusterConfiguration:
    apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
    clusterName: ibm-vpc-1
    controlPlaneEndpoint: 150.238.55.156:6443
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: "true"
    dns: {}
    etcd: {}
    kubernetesVersion: v1.14.3
    networking:
      dnsDomain: cluster.local
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.128.0.0/12
    scheduler: {}
  initConfiguration:
    localAPIEndpoint:
      advertiseAddress: ""
      bindPort: 0
    nodeRegistration:
      criSocket: /var/run/containerd/containerd.sock
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%