apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1    
  name: worker-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: worker-0-config
      namespace: default
  clusterName: ibm-vpc-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCMachine
    name: worker-0
    namespace: default
  providerID: ibmvpc:////ibm-vpc-1-worker-0
  version: v1.14.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: worker-0
spec:
  name: worker-0
  providerID: ibmvpc:////ibm-vpc-1-worker-0
  image: r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4
  zone: us-south-1
  profile: bx2-4x16
  primaryNetworkInterface: 
    subnet: 0716-f692d3f9-585a-465d-962d-a1696a12fe12